# User.create([
    #     { name: 'Jon', size: 'M', age: 31},
    #     { name: 'A', size: 'L', age: 22},
    #     { name: 'B', size: 'XL', age: 31},
    #     { name: 'C', size: 'S', age: 25},
    #     { name: 'D', size: 'XL', age: 44},
    #   ])
    
Color.create([
    {name: 'Violet', url: 'https://i.imgur.com/4seabvo.png', swatch: 'https://i.imgur.com/FWFWLdv.png?1', backURL: 'https://i.imgur.com/b5T4lMd.png'},
{name: 'Carolina Blue', url: 'https://i.imgur.com/Bl8wS7j.png', swatch: 'https://i.imgur.com/QGSJO5H.png?1', backURL: ''},
{name: 'Garnet', url: 'https://i.imgur.com/SnKMNmu.png', swatch: 'https://i.imgur.com/rNyjqzg.png?1', backURL: ''},
{name: 'Dark Chocolate', url: 'https://i.imgur.com/N0ag2oS.png', swatch: 'https://i.imgur.com/dwJIUxi.png?1', backURL: ''},
{name: 'Heliconia', url: 'https://i.imgur.com/sADSPUL.png', swatch: 'https://i.imgur.com/SBV2rWS.png?1', backURL: ''},
{name: 'Daisy', url: 'https://i.imgur.com/VfzqIrG.png', swatch: 'https://i.imgur.com/mqz7z3z.png?1', backURL: ''},
{name: 'Heather Sapphire', url: 'https://i.imgur.com/1yH8uWF.png', swatch: 'https://i.imgur.com/ZbPNYDJ.png?1', backURL: 'https://i.imgur.com/yYNgFee.png'},
{name: 'Ash', url: 'https://i.imgur.com/c5PV92A.png', swatch: 'https://i.imgur.com/0ULbN6y.png?1', backURL: ''},
{name: 'Forest Green', url: 'https://i.imgur.com/narQj3c.png', swatch: 'https://i.imgur.com/bgPhz1E.png?1', backURL: ''},
{name: 'Heather Military Green', url: 'https://i.imgur.com/G7eE4BV.png', swatch: 'https://i.imgur.com/CrJYXVq.png?1', backURL: ''},
{name: 'Coral Silk', url: 'https://i.imgur.com/qOycyGc.png', swatch: 'https://i.imgur.com/5Nihsyr.png?1', backURL: ''},
{name: 'Azalea', url: 'https://i.imgur.com/zDOBXB5.png', swatch: 'https://i.imgur.com/wzMTiZ6.png?1', backURL: ''},
{name: 'Gold', url: 'https://i.imgur.com/cldVK2G.png', swatch: 'https://i.imgur.com/YmwnHmG.png?1', backURL: ''},
{name: 'Heather Red', url: 'https://i.imgur.com/Iw9b4fB.png', swatch: 'https://i.imgur.com/wlMKNoT.png?1', backURL: ''},
{name: 'Charcoal', url: 'https://i.imgur.com/C8nCyXM.png', swatch: 'https://i.imgur.com/FCWvtUu.png?1', backURL: ''},
{name: 'Brown Savana', url: 'https://i.imgur.com/287fd67.png', swatch: 'https://i.imgur.com/eIoFQDE.png?1', backURL: ''},
{name: 'Tennessee Orange', url: 'https://i.imgur.com/mUQUp05.png', swatch: 'https://i.imgur.com/UkJxHsI.png?1', backURL: 'https://i.imgur.com/eQe4iDL.png'},
{name: 'Sapphire', url: 'https://i.imgur.com/8HAnd86.png', swatch: 'https://i.imgur.com/csRgXdr.png?1', backURL: 'https://i.imgur.com/dW2Las1.png'},
{name: 'Old Gold', url: 'https://i.imgur.com/gFCfRVv.png', swatch: 'https://i.imgur.com/7izoVwj.png?1', backURL: ''},
{name: 'Sand', url: 'https://i.imgur.com/Z8Vctx1.png', swatch: 'https://i.imgur.com/IEZTDVp.png?1', backURL: 'https://i.imgur.com/ZA94C5s.png'},
{name: 'Purple', url: 'https://i.imgur.com/rmd3Kzv.png', swatch: 'https://i.imgur.com/tv9CigL.png?1', backURL: 'https://i.imgur.com/Qya0mTN.png'},
{name: 'Yellow Haze', url: 'https://i.imgur.com/0AwFwih.png', swatch: 'https://i.imgur.com/rGcqTgA.png?1', backURL: 'https://i.imgur.com/A5dxZqx.png'},
{name: 'Sky', url: 'https://i.imgur.com/PyyhvZN.png', swatch: 'https://i.imgur.com/QGsoSOT.png?1', backURL: 'https://i.imgur.com/iQx0JjM.png'},
{name: 'Orange', url: 'https://i.imgur.com/0qIItyE.png', swatch: 'https://i.imgur.com/ZGZSRpl.png?1', backURL: ''},
{name: 'Navy', url: 'https://i.imgur.com/yirOj0Z.png', swatch: 'https://i.imgur.com/3QR9ZoE.png?1', backURL: ''},
{name: 'Maroon', url: 'https://i.imgur.com/lIl04D4.png', swatch: 'https://i.imgur.com/3o8ZMuV.png?1', backURL: ''},
{name: 'Military Green', url: 'https://i.imgur.com/sMViQir.png', swatch: 'https://i.imgur.com/jUtV9fX.png?1', backURL: ''},
{name: 'Natural', url: 'https://i.imgur.com/9nCy3l6.png', swatch: 'https://i.imgur.com/lrVpujL.png?1', backURL: ''},
{name: 'Tweed', url: 'https://i.imgur.com/2mnaRdY.png', swatch: 'https://i.imgur.com/SNgtfHU.png?1', backURL: 'https://i.imgur.com/1cjeE67.png'},
{name: 'Light Pink', url: 'https://i.imgur.com/yPVHZG8.png', swatch: 'https://i.imgur.com/afBfFaz.png?1', backURL: ''},
{name: 'Turf Green', url: 'https://i.imgur.com/ee712KW.png', swatch: 'https://i.imgur.com/u1xOlmM.png?1', backURL: 'https://i.imgur.com/A5dxZqx.png'},
{name: 'Lime', url: 'https://i.imgur.com/HWdOAjN.png', swatch: 'https://i.imgur.com/3IOJnTQ.png?1', backURL: ''},
{name: 'Sport Grey', url: 'https://i.imgur.com/6rHr7N5.png', swatch: 'https://i.imgur.com/btHad9H.png?1', backURL: 'https://i.imgur.com/YLtinXU.png'},
{name: 'Ice Grey', url: 'https://i.imgur.com/ssFw5RP.png', swatch: 'https://i.imgur.com/mYnztmS.png?1', backURL: ''},
{name: 'Light Blue', url: 'https://i.imgur.com/UIxZRz4.png', swatch: 'https://i.imgur.com/xlddzzM.png?1', backURL: ''},
{name: 'Indigo Blue', url: 'https://i.imgur.com/rXnliWZ.png', swatch: 'https://i.imgur.com/DGqnd9s.png?1', backURL: ''},
{name: 'Irish Green', url: 'https://i.imgur.com/VWPhiCe.png', swatch: 'https://i.imgur.com/4uWJzui.png?1', backURL: ''},
{name: 'Kiwi', url: 'https://i.imgur.com/FqJDpkS.png', swatch: 'https://i.imgur.com/CcLU32S.png?1', backURL: ''},
{name: 'Gravel', url: 'https://i.imgur.com/YxV6AKi.png', swatch: 'https://i.imgur.com/EmhZwyP.png?1', backURL: ''},
{name: 'Russet', url: 'https://i.imgur.com/b4cKWw7.png', swatch: 'https://i.imgur.com/NlQWWAT.png?1', backURL: 'https://i.imgur.com/kxjm5UU.png'},
{name: 'Red', url: 'https://i.imgur.com/mViYeXD.png', swatch: 'https://i.imgur.com/qMUfyoq.png?1', backURL: 'https://i.imgur.com/gWN9y7u.png'},
{name: 'Royal', url: 'https://i.imgur.com/c5vM1zr.png', swatch: 'https://i.imgur.com/HJijToh.png?1', backURL: 'https://i.imgur.com/reUwrXK.png'},
{name: 'Berry', url: 'https://i.imgur.com/jfr2tBu.png', swatch: 'https://i.imgur.com/ktpZKg6.png?1', backURL: ''},
{name: 'Blackberry', url: 'https://i.imgur.com/zxqQiU4.png', swatch: 'https://i.imgur.com/nKcC8p6.png?1', backURL: ''},
{name: 'Cardinal', url: 'https://i.imgur.com/1b6keFN.png', swatch: 'https://i.imgur.com/ma39P2R.png?1', backURL: ''},
{name: 'Antique Orange', url: 'https://i.imgur.com/BbSiIRg.png', swatch: 'https://i.imgur.com/VN6FrqF.png?1', backURL: ''},
{name: 'Antique Jade Dome', url: 'https://i.imgur.com/kjvQB1T.png', swatch: 'https://i.imgur.com/VMElfpM.png?1', backURL: ''},
{name: 'Antique Sapphire ', url: 'https://i.imgur.com/gANhHUv.png', swatch: 'https://i.imgur.com/ngXQw5Z.png?1', backURL: ''},
{name: 'Antique Irish Green', url: 'https://i.imgur.com/fJuHLEB.png', swatch: 'https://i.imgur.com/WmNrcXU.png?1', backURL: ''},
{name: 'Antique Cherry Red', url: 'https://i.imgur.com/gMWwuwW.png', swatch: 'https://i.imgur.com/G6FqMNv.png?1', backURL: ''},
{name: 'Tropical Blue', url: 'https://i.imgur.com/DU2swvF.png', swatch: 'https://i.imgur.com/CUvte65.png?1', backURL: 'https://i.imgur.com/ooOCZxX.png'},
{name: 'Texas Orange', url: 'https://i.imgur.com/tjxci7H.png', swatch: 'https://i.imgur.com/qyvagnL.png?1', backURL: 'https://i.imgur.com/2pg3QaC.png'},
{name: 'White', url: 'https://i.imgur.com/NK1xHNf.png', swatch: 'https://i.imgur.com/ft2VKS2.png?1', backURL: 'https://i.imgur.com/yJKX0p3.png'},
{name: 'Neon Blue', url: 'https://i.imgur.com/YJGIxxm.png', swatch: 'https://i.imgur.com/34YihC8.png?1', backURL: ''},
{name: 'Safety Pink', url: 'https://i.imgur.com/4SICdD6.png', swatch: 'https://i.imgur.com/XBOf4qm.png?1', backURL: 'https://i.imgur.com/iMzCYga.png'},
{name: 'Safety Green', url: 'https://i.imgur.com/UncnUcM.png', swatch: 'https://i.imgur.com/6m5Rtu4.png?1', backURL: 'https://i.imgur.com/NhfBRMn.png'},
{name: 'Heather Radiant Orchid', url: 'https://i.imgur.com/YchU3py.png', swatch: 'https://i.imgur.com/Gh7tKok.png?1', backURL: ''},
{name: 'Neon Green', url: 'https://i.imgur.com/KCZR1T9.png', swatch: 'https://i.imgur.com/Yp20SGE.png?1', backURL: ''},
{name: 'Midnight', url: 'https://i.imgur.com/AeWVvuU.png', swatch: 'https://i.imgur.com/L3pzfSV.png?1', backURL: ''},
{name: 'Safety Orange', url: 'https://i.imgur.com/WwwwA9O.png', swatch: 'https://i.imgur.com/okcAvPQ.png?1', backURL: 'https://i.imgur.com/uujZmxc.png'},
{name: 'Sunset', url: 'https://i.imgur.com/PfLdhUf.png', swatch: 'https://i.imgur.com/JOnngNd.png?1', backURL: 'https://i.imgur.com/sp5BGMo.png'},
{name: 'Dark Heather', url: 'https://i.imgur.com/lK8R9cR.png', swatch: 'https://i.imgur.com/BCzvAQr.png?1', backURL: ''},
{name: 'Lilac', url: 'https://i.imgur.com/qzIKN1c.png', swatch: 'https://i.imgur.com/8aEPTi9.png?1', backURL: ''},
{name: 'Graphite Heather', url: 'https://i.imgur.com/RYAOhNZ.png', swatch: 'https://i.imgur.com/alROoo6.png?1', backURL: ''},
{name: 'Cornsilk', url: 'https://i.imgur.com/mahJzJJ.png', swatch: 'https://i.imgur.com/Jusqr1g.png?1', backURL: ''},
{name: 'Heather Navy', url: 'https://i.imgur.com/iAeA2Kl.png', swatch: 'https://i.imgur.com/R7fzzhg.png?1', backURL: ''},
{name: 'Mint Green', url: 'https://i.imgur.com/axLLSZZ.png', swatch: 'https://i.imgur.com/g855CYl.png?1', backURL: ''},
{name: 'Electric Green', url: 'https://i.imgur.com/ahEtgPJ.png', swatch: 'https://i.imgur.com/rzpvnel.png?1', backURL: ''},
{name: 'Cobalt', url: 'https://i.imgur.com/5VEBiQF.png', swatch: 'https://i.imgur.com/FNBLc9T.png?1', backURL: ''},
{name: 'Black', url: 'https://i.imgur.com/mjKPh7f.png', swatch: 'https://i.imgur.com/MZFTieP.png?1', backURL: ''},


])
    

#   Item.create([
#     { style: 'shirt', size: 'S', color: 'blue', price: 10, user_id: 1},
#     { style: 'shirt', size: 'M', color: 'red', price: 12, user_id: 1},
#     { style: 'shirt', size: 'S', color: 'yellow', price: 10, user_id: 1},
#     { style: 'shirt', size: 'S', color: 'blue', price: 10, user_id: 2},
#     { style: 'shirt', size: 'L', color: 'red', price: 12, user_id: 2},
#     { style: 'shirt', size: 'S', color: 'yellow', price: 10, user_id: 2},
#     { style: 'shirt', size: 'XL', color: 'orange', price: 13, user_id: 2},
#     { style: 'shirt', size: 'M', color: 'red', price: 12, user_id: 2},
#     { style: 'shirt', size: 'S', color: 'pink', price: 10, user_id: 2},
#     { style: 'hat', size: 'S', color: 'yellow', price: 10, user_id: 3}
#   ])
  
#    Color.create([
#      {name: 'pink'},
#      {name: 'yellow'},
#      {name: 'blue'},
#      {name: 'red'},
#      {name: 'white'},
#      {name: 'black'},
#    ])
    
# Logo.create([
#          { name: 'https://i.imgur.com/2FPatyw.png?1', user_id: 1},
#          { name: 'https://i.imgur.com/eWUVgIV.png?1', user_id: 2},
#          { name: 'https://i.imgur.com/cq1KbYO.png?1', user_id: 2},
#          { name: 'https://i.imgur.com/wdU3TLw.png?1', user_id: 3},
# ])

