User.create([
    name: '1', age: 2, size: '3'
])

Logo.create([
    name: 'https://jweinst4.s3.amazonaws.com/Test/Air-Jordan-1-Bred-Toe-Womens-GS-Red-And-Black-Jordans-Shoes-575441-610-(1)-1300x1300.jpg',
    user_id: 1,
])
    
Color.create([

    {name: 'Violet', url: 'https://i.imgur.com/4seabvo.png', swatch: 'https://i.imgur.com/FWFWLdv.png?1', backURL: 'https://i.imgur.com/2iILQgP.png'},
    {name: 'Carolina Blue', url: 'https://i.imgur.com/Bl8wS7j.png', swatch: 'https://i.imgur.com/QGSJO5H.png?1', backURL: 'https://i.imgur.com/3BKbQdN.png'},
    {name: 'Garnet', url: 'https://i.imgur.com/SnKMNmu.png', swatch: 'https://i.imgur.com/rNyjqzg.png?1', backURL: 'https://i.imgur.com/yULLgzR.png'},
    {name: 'Dark Chocolate', url: 'https://i.imgur.com/N0ag2oS.png', swatch: 'https://i.imgur.com/dwJIUxi.png?1', backURL: 'https://i.imgur.com/bd9MEF7.png'},
    {name: 'Heliconia', url: 'https://i.imgur.com/sADSPUL.png', swatch: 'https://i.imgur.com/SBV2rWS.png?1', backURL: 'https://i.imgur.com/iEWXi5L.png'},
    {name: 'Daisy', url: 'https://i.imgur.com/VfzqIrG.png', swatch: 'https://i.imgur.com/mqz7z3z.png?1', backURL: 'https://i.imgur.com/DGqmMVJ.png'},
    {name: 'Heather Sapphire', url: 'https://i.imgur.com/1yH8uWF.png', swatch: 'https://i.imgur.com/ZbPNYDJ.png?1', backURL: 'https://i.imgur.com/9AxIvq7.png'},
    {name: 'Ash', url: 'https://i.imgur.com/c5PV92A.png', swatch: 'https://i.imgur.com/0ULbN6y.png?1', backURL: 'https://i.imgur.com/3rj1rtq.png'},
    {name: 'Forest Green', url: 'https://i.imgur.com/narQj3c.png', swatch: 'https://i.imgur.com/bgPhz1E.png?1', backURL: 'https://i.imgur.com/DV9kagO.png'},
    {name: 'Heather Military Green', url: 'https://i.imgur.com/G7eE4BV.png', swatch: 'https://i.imgur.com/CrJYXVq.png?1', backURL: 'https://i.imgur.com/ULoMENH.png'},
    {name: 'Coral Silk', url: 'https://i.imgur.com/qOycyGc.png', swatch: 'https://i.imgur.com/5Nihsyr.png?1', backURL: 'https://i.imgur.com/r85i4ZN.png'},
    {name: 'Azalea', url: 'https://i.imgur.com/zDOBXB5.png', swatch: 'https://i.imgur.com/wzMTiZ6.png?1', backURL: 'https://i.imgur.com/Xb9ctrA.png'},
    {name: 'Gold', url: 'https://i.imgur.com/cldVK2G.png', swatch: 'https://i.imgur.com/YmwnHmG.png?1', backURL: 'https://i.imgur.com/YXxkzIw.png'},
    {name: 'Heather Red', url: 'https://i.imgur.com/Iw9b4fB.png', swatch: 'https://i.imgur.com/wlMKNoT.png?1', backURL: 'https://i.imgur.com/PIeQEwQ.png'},
    {name: 'Charcoal', url: 'https://i.imgur.com/C8nCyXM.png', swatch: 'https://i.imgur.com/FCWvtUu.png?1', backURL: 'https://i.imgur.com/oHg5hMG.png'},
    {name: 'Brown Savana', url: 'https://i.imgur.com/287fd67.png', swatch: 'https://i.imgur.com/eIoFQDE.png?1', backURL: 'https://i.imgur.com/SnnsBrX.png'},
    {name: 'Tennessee Orange', url: 'https://i.imgur.com/mUQUp05.png', swatch: 'https://i.imgur.com/UkJxHsI.png?1', backURL: 'https://i.imgur.com/b2Vj2Jn.png'},
    {name: 'Sapphire', url: 'https://i.imgur.com/8HAnd86.png', swatch: 'https://i.imgur.com/csRgXdr.png?1', backURL: 'https://i.imgur.com/Yf2BZ0l.png'},
    {name: 'Old Gold', url: 'https://i.imgur.com/gFCfRVv.png', swatch: 'https://i.imgur.com/7izoVwj.png?1', backURL: 'https://i.imgur.com/XpuLxsk.png'},
    {name: 'Sand', url: 'https://i.imgur.com/Z8Vctx1.png', swatch: 'https://i.imgur.com/IEZTDVp.png?1', backURL: 'https://i.imgur.com/7hFc0I6.png'},
    {name: 'Purple', url: 'https://i.imgur.com/rmd3Kzv.png', swatch: 'https://i.imgur.com/tv9CigL.png?1', backURL: 'https://i.imgur.com/OCTM99y.png'},
    {name: 'Yellow Haze', url: 'https://i.imgur.com/0AwFwih.png', swatch: 'https://i.imgur.com/rGcqTgA.png?1', backURL: 'https://i.imgur.com/49lyCK8.png'},
    {name: 'Sky', url: 'https://i.imgur.com/PyyhvZN.png', swatch: 'https://i.imgur.com/QGsoSOT.png?1', backURL: 'https://i.imgur.com/BlJBA3U.png'},
    {name: 'Orange', url: 'https://i.imgur.com/0qIItyE.png', swatch: 'https://i.imgur.com/ZGZSRpl.png?1', backURL: 'https://i.imgur.com/rBLhfXm.png'},
    {name: 'Navy', url: 'https://i.imgur.com/yirOj0Z.png', swatch: 'https://i.imgur.com/3QR9ZoE.png?1', backURL: 'https://i.imgur.com/2stvse1.png'},
    {name: 'Maroon', url: 'https://i.imgur.com/lIl04D4.png', swatch: 'https://i.imgur.com/3o8ZMuV.png?1', backURL: 'https://i.imgur.com/5BekLCM.png'},
    {name: 'Military Green', url: 'https://i.imgur.com/sMViQir.png', swatch: 'https://i.imgur.com/jUtV9fX.png?1', backURL: 'https://i.imgur.com/2caovcr.png'},
    {name: 'Natural', url: 'https://i.imgur.com/9nCy3l6.png', swatch: 'https://i.imgur.com/lrVpujL.png?1', backURL: 'https://i.imgur.com/C5LhnKH.png'},
    {name: 'Tweed', url: 'https://i.imgur.com/2mnaRdY.png', swatch: 'https://i.imgur.com/SNgtfHU.png?1', backURL: 'https://i.imgur.com/o1fqgQa.png'},
    {name: 'Light Pink', url: 'https://i.imgur.com/yPVHZG8.png', swatch: 'https://i.imgur.com/afBfFaz.png?1', backURL: 'https://i.imgur.com/jO7yiss.png'},
    {name: 'Turf Green', url: 'https://i.imgur.com/ee712KW.png', swatch: 'https://i.imgur.com/u1xOlmM.png?1', backURL: 'https://i.imgur.com/UVhYY7A.png'},
    {name: 'Lime', url: 'https://i.imgur.com/HWdOAjN.png', swatch: 'https://i.imgur.com/3IOJnTQ.png?1', backURL: 'https://i.imgur.com/DDgKI0h.png'},
    {name: 'Sport Grey', url: 'https://i.imgur.com/6rHr7N5.png', swatch: 'https://i.imgur.com/btHad9H.png?1', backURL: 'https://i.imgur.com/StW7PW6.png'},
    {name: 'Ice Grey', url: 'https://i.imgur.com/ssFw5RP.png', swatch: 'https://i.imgur.com/mYnztmS.png?1', backURL: 'https://i.imgur.com/FDT3NBv.png'},
    {name: 'Light Blue', url: 'https://i.imgur.com/UIxZRz4.png', swatch: 'https://i.imgur.com/xlddzzM.png?1', backURL: 'https://i.imgur.com/bni1354.png'},
    {name: 'Indigo Blue', url: 'https://i.imgur.com/rXnliWZ.png', swatch: 'https://i.imgur.com/DGqnd9s.png?1', backURL: 'https://i.imgur.com/JSX4QXS.png'},
    {name: 'Irish Green', url: 'https://i.imgur.com/VWPhiCe.png', swatch: 'https://i.imgur.com/4uWJzui.png?1', backURL: 'https://i.imgur.com/bDhyN0n.png'},
    {name: 'Kiwi', url: 'https://i.imgur.com/FqJDpkS.png', swatch: 'https://i.imgur.com/CcLU32S.png?1', backURL: 'https://i.imgur.com/x3kiz0H.png'},
    {name: 'Gravel', url: 'https://i.imgur.com/YxV6AKi.png', swatch: 'https://i.imgur.com/EmhZwyP.png?1', backURL: 'https://i.imgur.com/20YsUXk.png'},
    {name: 'Russet', url: 'https://i.imgur.com/b4cKWw7.png', swatch: 'https://i.imgur.com/NlQWWAT.png?1', backURL: 'https://i.imgur.com/eJL0FR8.png'},
    {name: 'Red', url: 'https://i.imgur.com/mViYeXD.png', swatch: 'https://i.imgur.com/qMUfyoq.png?1', backURL: 'https://i.imgur.com/Y1oPh8X.png'},
    {name: 'Royal', url: 'https://i.imgur.com/c5vM1zr.png', swatch: 'https://i.imgur.com/HJijToh.png?1', backURL: 'https://i.imgur.com/ti6VQIp.png'},
    {name: 'Berry', url: 'https://i.imgur.com/jfr2tBu.png', swatch: 'https://i.imgur.com/ktpZKg6.png?1', backURL: 'https://i.imgur.com/4yxW87W.png'},
    {name: 'Blackberry', url: 'https://i.imgur.com/zxqQiU4.png', swatch: 'https://i.imgur.com/nKcC8p6.png?1', backURL: 'https://i.imgur.com/tD9sdSI.png'},
    {name: 'Cardinal', url: 'https://i.imgur.com/1b6keFN.png', swatch: 'https://i.imgur.com/ma39P2R.png?1', backURL: 'https://i.imgur.com/bSYXa5n.png'},
    {name: 'Antique Orange', url: 'https://i.imgur.com/BbSiIRg.png', swatch: 'https://i.imgur.com/VN6FrqF.png?1', backURL: 'https://i.imgur.com/hN6CFjl.png'},
    {name: 'Antique Jade Dome', url: 'https://i.imgur.com/kjvQB1T.png', swatch: 'https://i.imgur.com/VMElfpM.png?1', backURL: 'https://i.imgur.com/zYcZs71.png'},
    {name: 'Antique Sapphire ', url: 'https://i.imgur.com/gANhHUv.png', swatch: 'https://i.imgur.com/ngXQw5Z.png?1', backURL: 'https://i.imgur.com/PCH9RXg.png'},
    {name: 'Antique Irish Green', url: 'https://i.imgur.com/fJuHLEB.png', swatch: 'https://i.imgur.com/WmNrcXU.png?1', backURL: 'https://i.imgur.com/qCHe5FB.png'},
    {name: 'Antique Cherry Red', url: 'https://i.imgur.com/gMWwuwW.png', swatch: 'https://i.imgur.com/G6FqMNv.png?1', backURL: 'https://i.imgur.com/fvfcYRz.png'},
    {name: 'Tropical Blue', url: 'https://i.imgur.com/DU2swvF.png', swatch: 'https://i.imgur.com/CUvte65.png?1', backURL: 'https://i.imgur.com/OoFOrKj.png'},
    {name: 'Texas Orange', url: 'https://i.imgur.com/tjxci7H.png', swatch: 'https://i.imgur.com/qyvagnL.png?1', backURL: 'https://i.imgur.com/rPAsAkn.png'},
    {name: 'White', url: 'https://i.imgur.com/NK1xHNf.png', swatch: 'https://i.imgur.com/ft2VKS2.png?1', backURL: 'https://i.imgur.com/dXWaqQ1.png'},
    {name: 'Neon Blue', url: 'https://i.imgur.com/YJGIxxm.png', swatch: 'https://i.imgur.com/34YihC8.png?1', backURL: 'https://i.imgur.com/GKFqmMS.png'},
    {name: 'Safety Pink', url: 'https://i.imgur.com/4SICdD6.png', swatch: 'https://i.imgur.com/XBOf4qm.png?1', backURL: 'https://i.imgur.com/aNPGQge.png'},
    {name: 'Safety Green', url: 'https://i.imgur.com/UncnUcM.png', swatch: 'https://i.imgur.com/6m5Rtu4.png?1', backURL: 'https://i.imgur.com/oafzjfF.png'},
    {name: 'Heather Radiant Orchid', url: 'https://i.imgur.com/YchU3py.png', swatch: 'https://i.imgur.com/Gh7tKok.png?1', backURL: 'https://i.imgur.com/gIGWEZk.png'},
    {name: 'Neon Green', url: 'https://i.imgur.com/KCZR1T9.png', swatch: 'https://i.imgur.com/Yp20SGE.png?1', backURL: 'https://i.imgur.com/plHsFnC.png'},
    {name: 'Midnight', url: 'https://i.imgur.com/AeWVvuU.png', swatch: 'https://i.imgur.com/L3pzfSV.png?1', backURL: 'https://i.imgur.com/wgQvL2T.png'},
    {name: 'Safety Orange', url: 'https://i.imgur.com/WwwwA9O.png', swatch: 'https://i.imgur.com/okcAvPQ.png?1', backURL: 'https://i.imgur.com/Crg9Usx.png'},
    {name: 'Sunset', url: 'https://i.imgur.com/PfLdhUf.png', swatch: 'https://i.imgur.com/JOnngNd.png?1', backURL: 'https://i.imgur.com/cX3PkXk.png'},
    {name: 'Dark Heather', url: 'https://i.imgur.com/lK8R9cR.png', swatch: 'https://i.imgur.com/BCzvAQr.png?1', backURL: 'https://i.imgur.com/yiFkY4F.png'},
    {name: 'Lilac', url: 'https://i.imgur.com/qzIKN1c.png', swatch: 'https://i.imgur.com/8aEPTi9.png?1', backURL: 'https://i.imgur.com/BxKgfTf.png'},
    {name: 'Graphite Heather', url: 'https://i.imgur.com/RYAOhNZ.png', swatch: 'https://i.imgur.com/alROoo6.png?1', backURL: 'https://i.imgur.com/1Nulxp9.png'},
    {name: 'Cornsilk', url: 'https://i.imgur.com/mahJzJJ.png', swatch: 'https://i.imgur.com/Jusqr1g.png?1', backURL: 'https://i.imgur.com/EVKXQkx.png'},
    {name: 'Heather Navy', url: 'https://i.imgur.com/iAeA2Kl.png', swatch: 'https://i.imgur.com/R7fzzhg.png?1', backURL: 'https://i.imgur.com/FTv8BPn.png'},
    {name: 'Mint Green', url: 'https://i.imgur.com/axLLSZZ.png', swatch: 'https://i.imgur.com/g855CYl.png?1', backURL: 'https://i.imgur.com/Df9BmaQ.png'},
    {name: 'Electric Green', url: 'https://i.imgur.com/ahEtgPJ.png', swatch: 'https://i.imgur.com/rzpvnel.png?1', backURL: 'https://i.imgur.com/JA7U9Po.png'},
    {name: 'Cobalt', url: 'https://i.imgur.com/5VEBiQF.png', swatch: 'https://i.imgur.com/FNBLc9T.png?1', backURL: 'https://i.imgur.com/XfhbpxR.png'},
    {name: 'Black', url: 'https://i.imgur.com/mjKPh7f.png', swatch: 'https://i.imgur.com/MZFTieP.png?1', backURL: 'https://i.imgur.com/Vw2UbMz.png'},
])


